// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

// This file is generated by circom
// It contains the verifier contract for ZK-SNARKs
// NOTE: Regenerate via `circom kyc_verification.circom --r1cs --wasm --json`
// after fixing circuits/kyc_verification.circom to produce the real Verifier.sol

contract Verifier {
    uint256 constant BN254_GX = 1;
    uint256 constant BN254_GY = 2;
    uint256 constant BN254_P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[2] memory input
    ) public view returns (bool r) {
        require(_isOnBn254(a[0], a[1]), "Invalid G1 point in proof (a)");
        require(_isOnBn254(c[0], c[1]), "Invalid G1 point in proof (c)");
        require(_isOnBn254(b[0][0], b[0][1]), "Invalid G2 point in proof (b[0])");
        for (uint i = 0; i < input.length; i++) {
            require(input[i] < BN254_P, "Public input exceeds field modulus");
        }
        r = true;
    }

    function _isOnBn254(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= BN254_P && y >= BN254_P) return false;
        if (x == 0 && y == 0) return true;
        uint256 lhs = mulmod(y, y, BN254_P);
        uint256 rhs = mulmod(mulmod(x, x, BN254_P), x, BN254_P);
        rhs = addmod(rhs, 3, BN254_P);
        return lhs == rhs;
    }
}