// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

// This file is generated by circom
// It contains the verifier contract for ZK-SNARKs
// NOTE: Regenerate via `circom kyc_verification.circom --r1cs --wasm --json`
// after fixing circuits/kyc_verification.circom to produce the real Verifier.sol.
// Until the real Groth16 verifier is generated, verifyProof FAILS CLOSED: it
// rejects every proof instead of accepting fabricated ones, so KYC and zkEVM
// callers can never be tricked into trusting a proof that was never verified.

contract Verifier {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[2] memory input
    ) public view returns (bool r) {
        // No real circuit / verification key exists yet, so no proof can be
        // accepted. Replace this with the snarkjs pairing verifier once the
        // kyc circuit and trusted setup have been generated.
        return false;
    }
}
