name: truxify_driver
description: Driver-side Truxify web Flutter app.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  firebase_messaging: ^16.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  truxify_shared:
    path: ../../packages/truxify_shared

  supabase_flutter: ^2.9.1
  web_socket_channel: ^3.0.0

  google_fonts: ^8.1.0
  flutter_riverpod: ^2.5.1
  flutter_map: ^8.1.1
  latlong2: ^0.10.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  shimmer: ^3.0.0
  permission_handler: ^12.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  share_plus: ^13.2.1
  pdf: ^3.11.2
  printing: ^5.13.4
  camera: ^0.12.0+2
  signature: ^6.3.0
  image_picker: ^1.1.2
  connectivity_plus: ^7.2.0
  battery_plus: ^6.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: any
  mockito: ^5.4.4
  build_runner: ^2.4.8
  network_image_mock: ^2.1.1

flutter:
  generate: true
  uses-material-design: true
