apiVersion: telemetry.istio.io/v1alpha1
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: truxify-telemetry
  namespace: truxify
spec:
  metrics:
  - providers:
    - name: prometheus
  tracing:
  - providers:
    - name: jaeger
    randomSamplingPercentage: 50

  accessLogging:
  - providers:
    - name: envoy
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_COUNT
      disabled: false
    - match:
        metric: REQUEST_DURATION
      disabled: false
    - match:
        metric: REQUEST_SIZE
      disabled: false

