# Liquibase Configuration
changeLogFile: changelog-master.xml
url: jdbc:postgresql://localhost:5432/truxify
username: postgres
password: password
driver: org.postgresql.Driver
liquibase.schemaName: public
liquibase.databaseChangeLogTableName: DATABASECHANGELOG
liquibase.databaseChangeLogLockTableName: DATABASECHANGELOGLOCK