/**
 * @openapi
 * components:
 *   schemas:
 *     BatchSyncRequest:
 *       type: object
 *       required:
 *         - events
 *         - idempotencyKey
 *       properties:
 *         events:
 *           type: array
 *           maxItems: 100
 *           items:
 *             type: object
 *             properties:
 *               id:
 *                 type: string
 *               trip_id:
 *                 type: string
 *                 nullable: true
 *               type:
 *                 type: string
 *               occurred_at:
 *                 type: string
 *                 format: date-time
 *               payload:
 *                 type: object
 *               retry_count:
 *                 type: integer
 *         idempotencyKey:
 *           type: string
 *     BatchSyncResponse:
 *       type: object
 *       properties:
 *         message:
 *           type: string
 *         processed_count:
 *           type: integer
 *     TripEventsResponse:
 *       type: object
 *       properties:
 *         trip_id:
 *           type: string
 *         events:
 *           type: array
 *           items:
 *             type: object
 *             properties:
 *               event_id:
 *                 type: string
 *               user_id:
 *                 type: string
 *               trip_id:
 *                 type: string
 *               event_type:
 *                 type: string
 *               event_timestamp:
 *                 type: string
 *                 format: date-time
 *               latitude:
 *                 type: number
 *                 nullable: true
 *               longitude:
 *                 type: number
 *                 nullable: true
 *               metadata:
 *                 type: object
 *               created_at:
 *                 type: string
 *                 format: date-time
 */

import express from 'express';
import { z } from 'zod';
import { supabase } from '../config/db.js';
import { authenticate } from '../middleware/auth.js';
import { userLimiter } from '../middleware/rateLimiter.js';
import { validateParams } from '../middleware/validate.js';
import { uuidParamSchema } from '../validation/requestSchemas.js';
import logger from '../middleware/logger.js';

const router = express.Router();

// ============================================================================
// 🛡️ OFFLINE SYNC VALIDATION SCHEMAS (ISSUE #362)
// ============================================================================

// Per-event-type payload validation
// otpDelivery events are strictly validated — only stopId allowed, no otp field
// All other event types pass through with generic payload validation
const otpDeliveryPayloadSchema = z.object({
  stopId: z.string().min(1),
}).strict();

function validateEventPayload(type, payload) {
  if (type === 'otpDelivery') {
    return otpDeliveryPayloadSchema.safeParse(payload);
  }
  if (type === 'gpsUpdate') {
    return z.object({
      lat: z.number().min(-90).max(90),
      lng: z.number().min(-180).max(180),
      timestampMs: z.number().int().positive().optional(),
    }).safeParse(payload);
  }
  return { success: true, data: payload };
}

const SENSITIVE_FIELDS = [
  'otp', 'delivery_otp', 'token', 'secret', 'password',
  'phone_number', 'driver_phone', 'customer_phone', 'email',
  'current_location', 'driver_location',
  'license_number', 'aadhaar_number', 'pan_number',
];

function deepSanitize(obj, keys) {
  if (obj === null || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(item => deepSanitize(item, keys));
  const clean = {};
  for (const [k, v] of Object.entries(obj)) {
    if (keys.includes(k)) continue;
    clean[k] = deepSanitize(v, keys);
  }
  return clean;
}

// Schema for an individual Trip Event from the Flutter offline database
const tripEventSchema = z.object({
  id: z.string().min(1, "Event ID is required"),
  trip_id: z.string().optional().nullable(),
  type: z.string().min(1, "Event type is required"),
  occurred_at: z.string().datetime("occurred_at must be a valid ISO 8601 date string"),
  payload: z.record(z.any()).optional().default({}),
  retry_count: z.number().int().nonnegative().optional().default(0)
});

// Schema for the Batch Payload generated by apps/customer/.../sync_engine.dart
const batchSyncSchema = z.object({
  events: z.array(tripEventSchema).max(100, "Maximum batch size exceeded (Limit: 100)"),
  idempotencyKey: z.string().min(1, "Idempotency key is required to prevent duplicates")
});

// Reusable Middleware for validating the batch payload
const validateBatchPayload = (schema) => (req, res, next) => {
  try {
    req.body = schema.parse(req.body);
    next();
  } catch (error) {
    if (error instanceof z.ZodError) {
      const formattedErrors = (error.issues || error.errors).map(err => ({
        field: err.path.join('.'),
        message: err.message
      }));
      // The Flutter app explicitly looks for 422 to stop retrying bad payloads
      return res.status(422).json({
        error: 'Unprocessable Entity: Malformed batch payload',
        details: formattedErrors
      });
    }
    next(error);
  }
};

// ============================================================================
// 📡 OFFLINE SYNC ENDPOINT: BATCH EVENT INGESTION
// ============================================================================

/**
 * @openapi
 * /api/v1/trips/events/batch:
 *   post:
 *     tags: [Trips]
 *     summary: Batch ingest offline trip events
 *     description: Handles batched telemetry and trip events uploaded by mobile clients after recovering from network loss. Supports idempotency to prevent duplicate processing.
 *     security:
 *       - BearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/BatchSyncRequest'
 *     responses:
 *       200:
 *         description: Empty batch acknowledged
 *       202:
 *         description: Batch processed successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/BatchSyncResponse'
 *       422:
 *         description: Malformed batch payload
 *       500:
 *         description: Database processing error
 */
/**
 * POST /api/v1/trips/events/batch
 * Handles batched telemetry and trip events uploaded by the mobile client
 * after recovering from network loss.
 */
router.post('/events/batch', authenticate, userLimiter, validateBatchPayload(batchSyncSchema), async (req, res) => {
  const { events, idempotencyKey } = req.body;
  const userId = req.user.id;

  if (events.length === 0) {
    // Flutter expects 200 or 202 for success.
    return res.status(200).json({ message: 'Empty batch received, nothing to process.' });
  }

  try {
    // 1. Check Idempotency (Prevent double processing)
    // We check if this exact batch has already been processed recently.
    const { data: existingBatch } = await supabase
      .from('processed_batches')
      .select('id')
      .eq('idempotency_key', idempotencyKey)
      .eq('user_id', userId)
      .maybeSingle();

    if (existingBatch) {
      logger.info('[SyncEngine] Ignored duplicate batch:', idempotencyKey);
      // Return 202 Accepted so the Flutter app marks them as synced locally
      return res.status(202).json({ message: 'Batch already processed.' });
    }

    // 2. Validate per-event-type payloads and strip sensitive fields
    for (const event of events) {
      const result = validateEventPayload(event.type, event.payload || {});
      if (!result.success) {
        logger.warn('[SyncEngine] Invalid payload for event', event.id, '(type:', event.type, '):', result.error.issues);
        return res.status(422).json({
          error: 'Unprocessable Entity: Invalid event payload for type ' + event.type,
          details: result.error.issues,
        });
      }
    }

    const recordsToInsert = events.map(event => {
      const lat = event.payload?.lat !== undefined ? Number(event.payload.lat) : null;
      const lng = event.payload?.lng !== undefined ? Number(event.payload.lng) : null;

      const safeMetadata = deepSanitize(event.payload, SENSITIVE_FIELDS);

      return {
        event_id: event.id,
        user_id: userId,
        trip_id: event.trip_id || null,
        event_type: event.type,
        event_timestamp: event.occurred_at,
        latitude: lat,
        longitude: lng,
        metadata: safeMetadata,
        created_at: new Date().toISOString()
      };
    });

    // 3. Bulk Insert / Upsert into the trip_events table
    // Upsert ensures that if a specific event ID already exists, it just updates it
    // rather than failing the whole batch.
    const { error: insertError } = await supabase
      .from('trip_events')
      .upsert(recordsToInsert, { onConflict: 'event_id' });

    if (insertError) {
      logger.error('[SyncEngine] Bulk Insert Failed:', insertError.message);
      // Return 500 so the Flutter app knows to apply exponential backoff and retry later
      return res.status(500).json({ error: 'Database failed to process batch.' });
    }

    // 4. Log the successful batch using the idempotency key
    // This prevents the same batch from being uploaded again if the client crashes
    // before it can mark them as synced in its local SQLite db.
    const { error: idempotencyError } = await supabase
      .from('processed_batches')
      .insert({
        idempotency_key: idempotencyKey,
        user_id: userId,
        event_count: events.length,
        processed_at: new Date().toISOString()
      });

    if (idempotencyError) {
      // Non-fatal error. We processed the events, but failed to log the key.
      logger.warn('[SyncEngine] Failed to log idempotency key:', idempotencyKey);
    }

    // 5. Respond with 202 Accepted
    // This triggers `return true;` in the Flutter SyncEngine, allowing it to
    // clear the local database queue.
    logger.info('[SyncEngine] Successfully processed batch of', events.length, 'events for User:', userId);
    return res.status(202).json({
      message: 'Batch processed successfully',
      processed_count: events.length
    });

  } catch (err) {
    logger.error('[SyncEngine] Critical processing error:', err.message);
    // 500 triggers the `_backoffDelay` in the Flutter app
    return res.status(500).json({ error: 'Internal server error during batch processing.' });
  }
});

// ============================================================================
// GET TRIP EVENTS (DRIVER, CUSTOMER, OR ADMIN)
// ============================================================================
/**
 * @openapi
 * /api/trips/{id}/events:
 *   get:
 *     tags: [Trips]
 *     summary: Get trip events
 *     description: Returns all telemetry/milestone events for a given trip, ordered chronologically. Accessible by trip driver, order customer, or admin.
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *       - in: query
 *         name: type
 *         schema:
 *           type: string
 *         description: Filter by event type (e.g., gpsUpdate)
 *       - in: query
 *         name: sort
 *         schema:
 *           type: string
 *           enum: [asc, desc]
 *           default: desc
 *       - in: query
 *         name: min_lat
 *         schema:
 *           type: number
 *       - in: query
 *         name: max_lat
 *         schema:
 *           type: number
 *       - in: query
 *         name: min_lng
 *         schema:
 *           type: number
 *       - in: query
 *         name: max_lng
 *         schema:
 *           type: number
 *     responses:
 *       200:
 *         description: Trip events with metadata
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/TripEventsResponse'
 *       403:
 *         description: Access denied
 *       404:
 *         description: Trip not found
 */
/**
 * GET /api/trips/:id/events
 *
 * Returns all telemetry/milestone events for a given trip, ordered
 * chronologically.
 *
 * Access control:
 *   - The trip's driver (trip_events.user_id === req.user.id)
 *   - The order's customer (orders.customer_id === req.user.id)
 *   - Any admin
 *
 * Optional query param: ?type=gpsUpdate  (filters by event_type)
 */
router.get('/:id/events', authenticate, userLimiter, validateParams(uuidParamSchema), async (req, res) => {
  const tripId = req.params.id;
  const { type, sort, min_lat, max_lat, min_lng, max_lng } = req.query;
  const isAscending = sort !== 'desc';

  try {
    // 1. Fetch the trip to determine the driver
    const { data: events, error: eventsErr } = await supabase
      .from('trip_events')
      .select('event_id, user_id, trip_id, event_type, event_timestamp, latitude, longitude, metadata, created_at')
      .eq('trip_id', tripId)
      .order('event_timestamp', { ascending: isAscending });

    if (eventsErr) {
      return res.status(500).json({
        error: 'Failed to fetch trip events.',
        code: 'TRIP_EVENTS_FETCH_ERROR',
        details: eventsErr.message,
        timestamp: new Date().toISOString(),
      });
    }

    if (!events || events.length === 0) {
      // Check if the trip even exists
      const { data: existingEvent, error: existingEventErr } = await supabase
        .from('trip_events')
        .select('trip_id')
        .eq('trip_id', tripId)
        .limit(1)
        .maybeSingle();

      if (existingEventErr) {
        logger.error('[TripRoutes] Failed to check existing trip events:', existingEventErr.message);
        return res.status(500).json({ error: 'Internal Server Error' });
      }

      // If no events found at all, check via orders whether this trip/order exists
      const { data: order, error: orderErr } = await supabase
        .from('orders')
        .select('id, driver_id, customer_id')
        .eq('id', tripId)
        .maybeSingle();

      if (orderErr) {
        logger.error('[TripRoutes] Failed to check order for trip:', orderErr.message);
        return res.status(500).json({ error: 'Internal Server Error' });
      }

      if (!order && !existingEvent) {
        return res.status(404).json({ error: 'Trip not found.' });
      }

      // Authorisation check even for empty trips
      if (req.user.role !== 'admin') {
        const isDriver = order?.driver_id === req.user.id;
        const isCustomer = order?.customer_id === req.user.id;
        if (!isDriver && !isCustomer) {
          return res.status(403).json({ error: 'Access Denied: You are not authorised to view events for this trip.' });
        }
      }

      return res.json({ trip_id: tripId, events: [] });
    }

    // 2. Determine trip's driver from the first event's user_id (the driver who uploaded events)
    const driverUserId = events[0]?.user_id;

    // 3. Also look up the linked order to check customer access
    const { data: order, error: orderErr } = await supabase
      .from('orders')
      .select('id, driver_id, customer_id')
      .eq('id', tripId)
      .maybeSingle();

    if (orderErr) {
      logger.error(`[TripEvents] Failed to look up order for trip ${tripId}: ${orderErr.message}`);
      return res.status(500).json({ error: 'Internal Server Error' });
    }

    // 4. Access control
    if (req.user.role !== 'admin') {
      const isDriver = driverUserId === req.user.id || order?.driver_id === req.user.id;
      const isCustomer = order?.customer_id === req.user.id;
      if (!isDriver && !isCustomer) {
        return res.status(403).json({ error: 'Access Denied: You are not authorised to view events for this trip.' });
      }
    }

    // 5. Optional type filter
    let filteredEvents = events;
    if (type && typeof type === 'string') {
      filteredEvents = events.filter(e => e.event_type === type);
    }

    if (min_lat !== undefined || max_lat !== undefined || min_lng !== undefined || max_lng !== undefined) {
      filteredEvents = filteredEvents.filter(e => {
        if (e.latitude === null || e.longitude === null || e.latitude === undefined || e.longitude === undefined) return false;
        const lat = Number(e.latitude);
        const lng = Number(e.longitude);
        if (min_lat !== undefined && lat < Number(min_lat)) return false;
        if (max_lat !== undefined && lat > Number(max_lat)) return false;
        if (min_lng !== undefined && lng < Number(min_lng)) return false;
        if (max_lng !== undefined && lng > Number(max_lng)) return false;
        return true;
      });
    }

    return res.json({
      trip_id: tripId,
      events: filteredEvents,
    });
  } catch (err) {
    return res.status(500).json({ error: 'Internal Server Error', details: err.message });
  }
});

export default router;