import express from 'express';
import { z } from 'zod';
import { supabase } from '../config/db.js';
import { authenticate, requireRole } from '../middleware/auth.js';
import { userLimiter } from '../middleware/rateLimiter.js';
import logger from '../middleware/logger.js';

const router = express.Router();

// ============================================================================
// 🛡️ OFFLINE SYNC VALIDATION SCHEMAS (ISSUE #362)
// ============================================================================

// Per-event-type payload validation
// otpDelivery events are strictly validated — only stopId allowed, no otp field
// All other event types pass through with generic payload validation
const otpDeliveryPayloadSchema = z.object({
  stopId: z.string().min(1),
}).strict();

function validateEventPayload(type, payload) {
  if (type === 'otpDelivery') {
    return otpDeliveryPayloadSchema.safeParse(payload);
  }
  if (type === 'gpsUpdate') {
    return z.object({
      lat: z.number().min(-90).max(90),
      lng: z.number().min(-180).max(180),
      timestampMs: z.number().int().positive().optional(),
    }).safeParse(payload);
  }
  return { success: true, data: payload };
}

const SENSITIVE_FIELDS = ['otp', 'delivery_otp', 'token', 'secret', 'password'];

// Schema for an individual Trip Event from the Flutter offline database
const tripEventSchema = z.object({
  id: z.string().min(1, "Event ID is required"),
  trip_id: z.string().optional().nullable(),
  type: z.string().min(1, "Event type is required"),
  occurred_at: z.string().datetime("occurred_at must be a valid ISO 8601 date string"),
  payload: z.record(z.any()).optional().default({}),
  retry_count: z.number().int().nonnegative().optional().default(0)
});

// Schema for the Batch Payload generated by apps/customer/.../sync_engine.dart
const batchSyncSchema = z.object({
  events: z.array(tripEventSchema).max(100, "Maximum batch size exceeded (Limit: 100)"),
  idempotencyKey: z.string().min(1, "Idempotency key is required to prevent duplicates")
});

// Reusable Middleware for validating the batch payload
const validateBatchPayload = (schema) => (req, res, next) => {
  try {
    req.body = schema.parse(req.body);
    next();
  } catch (error) {
    if (error instanceof z.ZodError) {
      const formattedErrors = (error.issues || error.errors).map(err => ({
        field: err.path.join('.'),
        message: err.message
      }));
      // The Flutter app explicitly looks for 422 to stop retrying bad payloads
      return res.status(422).json({
        error: 'Unprocessable Entity: Malformed batch payload',
        details: formattedErrors
      });
    }
    next(error);
  }
};

function validateEventTripIds(events) {
  const missingIndex = events.findIndex(event => !event.trip_id);
  if (missingIndex !== -1) {
    return {
      ok: false,
      status: 400,
      error: `events.${missingIndex}.trip_id is required`,
    };
  }
  return { ok: true };
}

function hasCoordinatePayload(payload = {}) {
  return payload.lat !== undefined || payload.lng !== undefined;
}

async function verifyTripIdsBelongToUser(tripIds, user) {
  const uniqueTripIds = [...new Set(tripIds.filter(Boolean))];
  if (uniqueTripIds.length === 0) return { ok: true };

  const [ordersResult, tripsResult] = await Promise.all([
    supabase
      .from('orders')
      .select('id, driver_id, customer_id')
      .in('id', uniqueTripIds),
    supabase
      .from('trips')
      .select('id, driver_id')
      .in('id', uniqueTripIds),
  ]);

  if (ordersResult.error) {
    return { ok: false, status: 500, error: 'Failed to verify order ownership.' };
  }
  if (tripsResult.error) {
    return { ok: false, status: 500, error: 'Failed to verify trip ownership.' };
  }

  const orderById = new Map((ordersResult.data || []).map(order => [order.id, order]));
  const tripById = new Map((tripsResult.data || []).map(trip => [trip.id, trip]));

  for (const tripId of uniqueTripIds) {
    const order = orderById.get(tripId);
    const trip = tripById.get(tripId);

    if (!order && !trip) {
      return { ok: false, status: 404, error: `Trip not found: ${tripId}` };
    }

    if (user.role === 'admin') continue;

    const ownsOrder = order && (order.driver_id === user.id || order.customer_id === user.id);
    const ownsTrip = trip && trip.driver_id === user.id;

    if (!ownsOrder && !ownsTrip) {
      return { ok: false, status: 403, error: `Access denied for trip: ${tripId}` };
    }
  }

  return { ok: true };
}

// ============================================================================
// 📡 OFFLINE SYNC ENDPOINT: BATCH EVENT INGESTION
// ============================================================================

/**
 * POST /api/v1/trips/events/batch
 * Handles batched telemetry and trip events uploaded by the mobile client
 * after recovering from network loss.
 */
router.post('/events/batch', authenticate, userLimiter, validateBatchPayload(batchSyncSchema), async (req, res) => {
  const { events, idempotencyKey } = req.body;
  const userId = req.user.id;

  if (events.length === 0) {
    // Flutter expects 200 or 202 for success.
    return res.status(200).json({ message: 'Empty batch received, nothing to process.' });
  }

  try {
    // 1. Check Idempotency (Prevent double processing)
    // We check if this exact batch has already been processed recently.
    const { data: existingBatch } = await supabase
      .from('processed_batches')
      .select('id')
      .eq('idempotency_key', idempotencyKey)
      .eq('user_id', userId)
      .maybeSingle();

    if (existingBatch) {
      logger.info('[SyncEngine] Ignored duplicate batch:', idempotencyKey);
      // Return 202 Accepted so the Flutter app marks them as synced locally
      return res.status(202).json({ message: 'Batch already processed.' });
    }

    // 2. Validate per-event-type payloads and strip sensitive fields
    for (const event of events) {
      const result = validateEventPayload(event.type, event.payload || {});
      if (!result.success) {
        logger.warn('[SyncEngine] Invalid payload for event', event.id, '(type:', event.type, '):', result.error.issues);
        return res.status(422).json({
          error: 'Unprocessable Entity: Invalid event payload for type ' + event.type,
          details: result.error.issues,
        });
      }
    }

    const tripIdCheck = validateEventTripIds(events);
    if (!tripIdCheck.ok) {
      return res.status(tripIdCheck.status).json({ error: tripIdCheck.error });
    }

    const ownershipCheck = await verifyTripIdsBelongToUser(events.map(event => event.trip_id), req.user);
    if (!ownershipCheck.ok) {
      return res.status(ownershipCheck.status).json({ error: ownershipCheck.error });
    }

    const recordsToInsert = events.map(event => {
      const shouldMapCoordinates = event.type === 'gpsUpdate' || event.type === 'location_update';
      const lat = shouldMapCoordinates && event.payload?.lat !== undefined ? Number(event.payload.lat) : null;
      const lng = shouldMapCoordinates && event.payload?.lng !== undefined ? Number(event.payload.lng) : null;

      const safeMetadata = { ...event.payload };
      if (!shouldMapCoordinates && hasCoordinatePayload(safeMetadata)) {
        delete safeMetadata.lat;
        delete safeMetadata.lng;
      }
      for (const field of SENSITIVE_FIELDS) {
        delete safeMetadata[field];
      }

      return {
        event_id: event.id,
        user_id: userId,
        trip_id: event.trip_id || null,
        event_type: event.type,
        event_timestamp: event.occurred_at,
        latitude: lat,
        longitude: lng,
        metadata: safeMetadata,
        created_at: new Date().toISOString()
      };
    });

    // 3. Bulk Insert / Upsert into the trip_events table
    // Upsert ensures that if a specific event ID already exists, it just updates it
    // rather than failing the whole batch.
    const { error: insertError } = await supabase
      .from('trip_events')
      .upsert(recordsToInsert, { onConflict: 'event_id' });

    if (insertError) {
      logger.error('[SyncEngine] Bulk Insert Failed:', insertError.message);
      // Return 500 so the Flutter app knows to apply exponential backoff and retry later
      return res.status(500).json({ error: 'Database failed to process batch.' });
    }

    // 4. Log the successful batch using the idempotency key
    // This prevents the same batch from being uploaded again if the client crashes
    // before it can mark them as synced in its local SQLite db.
    const { error: idempotencyError } = await supabase
      .from('processed_batches')
      .insert({
        idempotency_key: idempotencyKey,
        user_id: userId,
        event_count: events.length,
        processed_at: new Date().toISOString()
      });

    if (idempotencyError) {
      // Non-fatal error. We processed the events, but failed to log the key.
      logger.warn('[SyncEngine] Failed to log idempotency key:', idempotencyKey);
    }

    // 5. Respond with 202 Accepted
    // This triggers `return true;` in the Flutter SyncEngine, allowing it to
    // clear the local database queue.
    logger.info('[SyncEngine] Successfully processed batch of', events.length, 'events for User:', userId);
    return res.status(202).json({
      message: 'Batch processed successfully',
      processed_count: events.length
    });

  } catch (err) {
    logger.error('[SyncEngine] Critical processing error:', err.message);
    // 500 triggers the `_backoffDelay` in the Flutter app
    return res.status(500).json({ error: 'Internal server error during batch processing.' });
  }
});

// ============================================================================
// GET TRIP EVENTS (DRIVER, CUSTOMER, OR ADMIN)
// ============================================================================
/**
 * @route GET /api/trips/:id/events
 * @desc Returns all telemetry and milestone events for a given trip, ordered chronologically.
 * @access Authenticated (Driver, Customer owner, or Admin)
 * @param {string} req.params.id - The UUID of the trip
 * @param {string} [req.query.type] - Filter by specific event type (e.g. gpsUpdate)
 * @param {string} [req.query.sort] - Chronological sort order ('asc' or 'desc', defaults to 'asc')
 * @param {number} [req.query.min_lat] - Minimum latitude for geographical bounding box filtering
 * @param {number} [req.query.max_lat] - Maximum latitude for geographical bounding box filtering
 * @param {number} [req.query.min_lng] - Minimum longitude for geographical bounding box filtering
 * @param {number} [req.query.max_lng] - Maximum longitude for geographical bounding box filtering
 * @returns {object} 200 - Trip ID and array of events
 * @returns {object} 400 - Validation errors for coordinates or sorting parameters
 * @returns {object} 403 - Forbidden if user is not driver, customer owner, or admin
 * @returns {object} 404 - Trip or order not found
 * @returns {object} 500 - Internal server error
 */
router.get('/:id/events', authenticate, userLimiter, async (req, res) => {
  const tripId = req.params.id;
  const { type, sort, min_lat, max_lat, min_lng, max_lng } = req.query;
  if (sort !== undefined && sort !== 'asc' && sort !== 'desc') {
    return res.status(400).json({ error: 'sort must be asc or desc' });
  }
  const isAscending = sort !== 'desc';
  const parseCoordinate = (value, name, min, max) => {
    if (value === undefined) return { value: undefined };
    if (typeof value !== 'string' || value.trim() === '') {
      return { error: `${name} must be a number` };
    }
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) {
      return { error: `${name} must be a number` };
    }
    if (parsed < min || parsed > max) {
      return { error: `${name} must be between ${min} and ${max}` };
    }
    return { value: parsed };
  };
  const minLat = parseCoordinate(min_lat, 'min_lat', -90, 90);
  const maxLat = parseCoordinate(max_lat, 'max_lat', -90, 90);
  const minLng = parseCoordinate(min_lng, 'min_lng', -180, 180);
  const maxLng = parseCoordinate(max_lng, 'max_lng', -180, 180);

  for (const result of [minLat, maxLat, minLng, maxLng]) {
    if (result.error) {
      return res.status(400).json({ error: result.error });
    }
  }
  if (minLat.value !== undefined && maxLat.value !== undefined && minLat.value > maxLat.value) {
    return res.status(400).json({ error: 'min_lat must be less than or equal to max_lat' });
  }
  if (minLng.value !== undefined && maxLng.value !== undefined && minLng.value > maxLng.value) {
    return res.status(400).json({ error: 'min_lng must be less than or equal to max_lng' });
  }

  try {
    const [orderResult, tripResult] = await Promise.all([
      supabase
        .from('orders')
        .select('id, driver_id, customer_id')
        .eq('id', tripId)
        .maybeSingle(),
      supabase
        .from('trips')
        .select('id, driver_id')
        .eq('id', tripId)
        .maybeSingle(),
    ]);

    if (orderResult.error) {
      return res.status(500).json({ error: 'Failed to verify order ownership.', details: orderResult.error.message });
    }
    if (tripResult.error) {
      return res.status(500).json({ error: 'Failed to verify trip ownership.', details: tripResult.error.message });
    }

    const order = orderResult.data;
    const trip = tripResult.data;
    if (!order && !trip) {
      return res.status(404).json({ error: 'Trip not found.' });
    }

    if (req.user.role !== 'admin') {
      const isOrderDriver = order?.driver_id === req.user.id;
      const isOrderCustomer = order?.customer_id === req.user.id;
      const isTripDriver = trip?.driver_id === req.user.id;
      if (!isOrderDriver && !isOrderCustomer && !isTripDriver) {
        return res.status(403).json({ error: 'Access Denied: You are not authorised to view events for this trip.' });
      }
    }

    // 1. Fetch the trip to determine the driver
    const { data: events, error: eventsErr } = await supabase
      .from('trip_events')
      .select('event_id, user_id, trip_id, event_type, event_timestamp, latitude, longitude, metadata, created_at')
      .eq('trip_id', tripId)
      .order('event_timestamp', { ascending: isAscending });

    if (eventsErr) {
      return res.status(500).json({ error: 'Failed to fetch trip events.', details: eventsErr.message });
    }

    if (!events || events.length === 0) {
      return res.json({ trip_id: tripId, events: [] });
    }

    // 5. Optional type filter
    let filteredEvents = events;
    if (type && typeof type === 'string') {
      filteredEvents = events.filter(e => e.event_type === type);
    }

    if (min_lat !== undefined || max_lat !== undefined || min_lng !== undefined || max_lng !== undefined) {
      if (min_lat !== undefined && !Number.isFinite(Number(min_lat))) {
        return res.status(400).json({ error: 'min_lat must be a valid number' });
      }
      if (max_lat !== undefined && !Number.isFinite(Number(max_lat))) {
        return res.status(400).json({ error: 'max_lat must be a valid number' });
      }
      if (min_lng !== undefined && !Number.isFinite(Number(min_lng))) {
        return res.status(400).json({ error: 'min_lng must be a valid number' });
      }
      if (max_lng !== undefined && !Number.isFinite(Number(max_lng))) {
        return res.status(400).json({ error: 'max_lng must be a valid number' });
      }
      filteredEvents = filteredEvents.filter(e => {
        if (e.latitude === null || e.longitude === null || e.latitude === undefined || e.longitude === undefined) return false;
        const lat = Number(e.latitude);
        const lng = Number(e.longitude);
        if (minLat.value !== undefined && lat < minLat.value) return false;
        if (maxLat.value !== undefined && lat > maxLat.value) return false;
        if (minLng.value !== undefined && lng < minLng.value) return false;
        if (maxLng.value !== undefined && lng > maxLng.value) return false;
        return true;
      });
    }

    return res.json({
      trip_id: tripId,
      events: filteredEvents,
    });
  } catch (err) {
    return res.status(500).json({ error: 'Internal Server Error', details: err.message });
  }
});

// ============================================================================
// MARK STOP COMPLETED (DRIVER)
// ============================================================================
router.put('/:tripDisplayId/stops/:stopId/complete', authenticate, userLimiter, requireRole(['driver']), async (req, res) => {
  const { tripDisplayId, stopId } = req.params;

  try {
    const { data: trip } = await supabase.from('trips').select('id').eq('trip_display_id', tripDisplayId).eq('driver_id', req.user.id).maybeSingle();
    if (!trip) return res.status(403).json({ error: 'Access Denied: Trip does not belong to you.' });

    const updatedStop = await supabase.from('trip_stops').update({
      is_completed: true,
      is_current: false,
    }).eq('id', stopId).eq('trip_display_id', tripDisplayId).select().maybeSingle();

    if (updatedStop.error) {
      logger.error('[tripRoutes] Failed to update stop:', updatedStop.error.message);
      return res.status(500).json({ error: 'Database error while updating stop.' });
    }
    if (!updatedStop.data) return res.status(404).json({ error: 'Stop not found or does not belong to this trip.' });

    const nextStops = await supabase.from('trip_stops').select()
      .eq('trip_display_id', tripDisplayId)
      .eq('is_completed', false)
      .order('sort_order')
      .limit(1);

    if (nextStops.data && nextStops.data.length > 0) {
      await supabase.from('trip_stops').update({ is_current: true })
        .eq('id', nextStops.data[0].id)
        .eq('trip_display_id', tripDisplayId);
    } else {
      await supabase.from('trips').update({ status: 'completed' })
        .eq('trip_display_id', tripDisplayId)
        .eq('driver_id', req.user.id);
    }

    res.json({ message: 'Stop marked as completed.' });
  } catch (err) {
    logger.error('[tripRoutes] markStopCompleted error:', err.message);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});

// ============================================================================
// START TRIP (DRIVER)
// ============================================================================
router.put('/:tripDisplayId/start', authenticate, userLimiter, requireRole(['driver']), async (req, res) => {
  const { tripDisplayId } = req.params;

  try {
    const { data: trip } = await supabase.from('trips').select('id').eq('trip_display_id', tripDisplayId).eq('driver_id', req.user.id).maybeSingle();
    if (!trip) return res.status(403).json({ error: 'Access Denied: Trip does not belong to you.' });

    const stops = await supabase.from('trip_stops').select()
      .eq('trip_display_id', tripDisplayId)
      .eq('is_completed', false)
      .order('sort_order')
      .limit(1);

    if (!stops.data || stops.data.length === 0) {
      return res.status(400).json({ error: 'No active stops found for this trip.' });
    }

    const firstStopId = stops.data[0].id;
    const updatedStop = await supabase.from('trip_stops').update({ is_current: true })
      .eq('id', firstStopId)
      .eq('trip_display_id', tripDisplayId)
      .select()
      .maybeSingle();

    if (!updatedStop.data) {
      return res.status(500).json({ error: 'Failed to start trip: Stop not found or update failed.' });
    }

    res.json({ message: 'Trip started.', stop_id: firstStopId });
  } catch (err) {
    logger.error('[tripRoutes] startTrip error:', err.message);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});

export default router;
