import { describe, it, expect, vi, beforeEach } from 'vitest';
import crypto from 'crypto';
import KeyRotationService from '../../../src/services/security/keyRotationService.js';

const mocks = vi.hoisted(() => ({
  supabaseInsert: vi.fn(),
}));

vi.mock('../../../src/config/db.js', () => ({
  default: {
    supabase: {
      from: vi.fn(() => ({
        insert: vi.fn(() => ({
          select: vi.fn(() => ({
            single: mocks.supabaseInsert
          }))
        })),
      }))
    }
  },
  supabase: {
    from: vi.fn(() => ({
      insert: vi.fn(() => ({
        select: vi.fn(() => ({
          single: mocks.supabaseInsert
        }))
      })),
      select: vi.fn(() => ({
        eq: vi.fn(() => ({
          eq: vi.fn(() => ({
            order: vi.fn(() => ({
              limit: vi.fn().mockResolvedValue({ data: [], error: null })
            }))
          }))
        }))
      })),
      update: vi.fn(() => ({
        eq: vi.fn().mockResolvedValue({ error: null })
      }))
    }))
  }
}));

vi.mock('../../../src/middleware/logger.js', () => ({
  default: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));

describe('KeyRotationService', () => {
  let service;

  beforeEach(() => {
    service = new KeyRotationService({});
    mocks.supabaseInsert.mockClear();
    mocks.supabaseInsert.mockResolvedValue({ data: { id: 1 }, error: null });
  });

  describe('createRotationRecord', () => {
    it('generates a standard UUID-based rotation ID', async () => {
      const rotationId = await service.createRotationRecord('user-1', '0x123', 'routine');
      
      expect(rotationId).toBeDefined();
      expect(rotationId.startsWith('rot_')).toBe(true);
      
      const uuidPart = rotationId.replace('rot_', '');
      
      // Standard UUID format regex (covers v4 generated by crypto.randomUUID)
      const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      expect(uuidRegex.test(uuidPart)).toBe(true);
    });

    it('generates unique collision-resistant IDs', async () => {
      const rotationId1 = await service.createRotationRecord('user-1', '0x123', 'routine');
      const rotationId2 = await service.createRotationRecord('user-1', '0x123', 'routine');
      
      expect(rotationId1).not.toBe(rotationId2);
    });
  });
});
