import logger from '../middleware/logger.js';
import { getHaversineDistance } from './routingService.js';

// Constants to simulate commercial work-zone impacts
const SEVERE_DELAY_THRESHOLD_MINS = 45;

/**
 * Predicts work-zone delays based on coordinates and departure time.
 * In a production environment, this would aggregate State DOT construction schedules,
 * live lane closure APIs, and historical heavy-traffic data.
 * 
 * @param {Object} start { lat, lng }
 * @param {Object} end { lat, lng }
 * @param {Array} waypoints [{ lat, lng }]
 * @param {string} departureDate YYYY-MM-DD
 * @param {string} departureTime HH:MM
 * @returns {Promise<Object>} { hasSevereDelay, predictedDelayMins, problematicPoint }
 */
export async function predictWorkZoneDelays(start, end, waypoints = [], departureDate, departureTime) {
  try {
    const allPoints = [start, ...waypoints, end].filter(p => p && p.lat && p.lng);
    if (allPoints.length === 0) {
      return { hasSevereDelay: false, predictedDelayMins: 0, problematicPoint: null };
    }

    // Combine date and time for seeding the predictive heuristic
    const timeString = `${departureDate || ''}T${departureTime || ''}`;
    // Simple numeric seed based on the string
    const timeSeed = timeString.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0) || 1;

    let maxDelayMins = 0;
    let worstPoint = null;

    for (const point of allPoints) {
      // Simulate historical traffic and DOT schedules using a pseudo-random hash of coords and time
      const latHash = Math.abs(Math.sin(Number(point.lat)) * 100);
      const lngHash = Math.abs(Math.cos(Number(point.lng)) * 100);
      
      // Some coordinates + time combinations will yield high delay spikes
      const delayScore = ((latHash + lngHash) * timeSeed) % 100; // 0 to 99

      if (delayScore > maxDelayMins) {
        maxDelayMins = delayScore;
        worstPoint = point;
      }
    }

    const hasSevereDelay = maxDelayMins >= SEVERE_DELAY_THRESHOLD_MINS;

    if (hasSevereDelay && worstPoint) {
      logger.info(`[WorkZoneService] Predicted severe commercial delay of ${maxDelayMins.toFixed(0)} mins at ${worstPoint.lat}, ${worstPoint.lng} on ${timeString}`);
    }

    return {
      hasSevereDelay,
      predictedDelayMins: maxDelayMins,
      problematicPoint: hasSevereDelay ? worstPoint : null
    };

  } catch (error) {
    logger.error(`[WorkZoneService] Error predicting work-zone delays: ${error.message}`);
    // Fail open: assume no severe delay if predictive engine fails
    return { hasSevereDelay: false, predictedDelayMins: 0, problematicPoint: null };
  }
}

/**
 * Generates an alternative bypass waypoint to force OSRM to route around the congested work zone.
 * 
 * @param {Object} congestedPoint { lat, lng }
 * @returns {Object} bypassWaypoint { lat, lng }
 */
export function generateBypassWaypoint(congestedPoint) {
  if (!congestedPoint || !congestedPoint.lat || !congestedPoint.lng) {
    return null;
  }

  // To bypass a congested point (e.g. radius of 5km), we shift the coordinate perpendicularly.
  // 1 degree of latitude is ~111 km. To shift by ~7 km:
  const shiftDegrees = 7 / 111;

  // We'll apply a simple static offset. In a real GIS engine, we'd find the nearest alternative highway.
  // For now, shifting latitude slightly forces the routing engine (OSRM) to use a different arterial road.
  const bypassLat = Number(congestedPoint.lat) + shiftDegrees;
  const bypassLng = Number(congestedPoint.lng) + shiftDegrees;

  logger.info(`[WorkZoneService] Generated bypass waypoint at ${bypassLat.toFixed(5)}, ${bypassLng.toFixed(5)} to avoid work zone at ${congestedPoint.lat}, ${congestedPoint.lng}`);

  return {
    lat: bypassLat,
    lng: bypassLng,
    address: 'Predictive Bypass Waypoint'
  };
}
